/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BeansConfigDialog.java
 *
 * Created on 14.03.2011, 17:52:31
 */

package de.lmu.ifi.dbs.trafficmining;

/**
 *
 * @author graf
 */
public class BeansConfigDialog extends javax.swing.JDialog {

    /** Creates new form BeansConfigDialog */
    public BeansConfigDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setBean(Object bean) throws Exception{
        beanTable.setBean(bean);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        beanTable = new de.lmu.ifi.dbs.beansUI.BeanTable();
        southPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configure");
        setModal(true);

        scrollPane.setViewportView(beanTable);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        southPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 1));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        southPanel.add(jButton1);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BeansConfigDialog dialog = new BeansConfigDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.lmu.ifi.dbs.beansUI.BeanTable beanTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables

}
