package de.lmu.ifi.dbs.beansUI.test;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

public class BeanConfigFrame extends javax.swing.JFrame {

    /** Creates new form BeanConfigFrame */
    public BeanConfigFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        beanTable1 = new de.lmu.ifi.dbs.beansUI.BeanTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(beanTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    BeanConfigFrame tf = new BeanConfigFrame();
                    tf.setVisible(true);
                    tf.beanTable1.setBean(new MyTestBean());
                } catch (Exception ex) {
                    Logger.getLogger(BeanConfigFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.lmu.ifi.dbs.beansUI.BeanTable beanTable1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
